version: '3.2'

services:
  kacmalpka-mysql:
    image: "mysql:5.7"
    container_name: kacmalpka-mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    ulimits:
      nofile:
        soft: "1024"
        hard: "2048"
    environment:
      - MYSQL_ROOT_PASSWORD=rootkacmalpka
      - MYSQL_DATABASE=kacmalpka
      - MYSQL_USER=kacmalpka
      - MYSQL_PASSWORD=kacmalpka
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


  kacmalpka-app:
    build: ./kacmalpka-app
    container_name: kacmalpka-app
    volumes:
      - ./kacmalpka-app:/app
    environment:
      - DB_SERVER=kacmalpka-mysql
    ports:
      - 8000:8000
    links:
      - kacmalpka-mysql
    depends_on:
      kacmalpka-mysql:
        condition: service_healthy


  kacmalpka-fe:
    build: ./kacmalpka-fe
    container_name: kacmalpka-fe
    volumes:
      - /react/node_modules
      - ./kacmalpka-fe:/react
    ports:
      - 3000:3000
    links:
      - kacmalpka-app


volumes:
  dbdata:
  
