version: '3'
services:

  kacmalpka-mysql:
    image: "mysql:5.7"
    container_name: kacmalpka-mysql
    volumes:
      - kacmalpka-data:/var/lib/mysql/data
    ports:
      - 5432:5432
    environment:
      - MYSQL_DB:kacmalpka
      - MYSQL_USER:kacmalpka
      - MYSQL_PASSWORD:kacmalpka

  kacmalpka-app:
    build: ./kacmalpka-app
    container_name: kacmalpka-app
    environment:
      - DB_SERVER=kacmalpka-mysql
    ports:
      - 8000:8000
    links:
      - kacmalpka-postgres

  kacmalpka-fe:
    build: ./kacmalpka-fe
    container_name: kacmalpka-fe
    ports:
      - 4200:80
    links:
      - kacmalpka-app


volumes:
  kacmalpka-data: