
DROP TABLE addresses CASCADE CONSTRAINTS;
DROP TABLE prices CASCADE CONSTRAINTS;
DROP TABLE product_tags CASCADE CONSTRAINTS;
DROP TABLE products CASCADE CONSTRAINTS;
DROP TABLE reviews CASCADE CONSTRAINTS;
DROP TABLE roles CASCADE CONSTRAINTS;
DROP TABLE tags CASCADE CONSTRAINTS;
DROP TABLE transaction_products CASCADE CONSTRAINTS;
DROP TABLE transactions CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
