# Generated by Django 3.2.7 on 2023-12-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('adrs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('adrs_line1', models.CharField(max_length=255)),
                ('adrs_line2', models.CharField(max_length=1023)),
                ('adrs_zipcode', models.CharField(max_length=127)),
                ('adrs_city', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_name_short', models.CharField(max_length=255)),
                ('prod_name_long', models.CharField(max_length=1023, null='True')),
                ('prod_description', models.CharField(max_length=10000)),
                ('prod_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_descr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('usr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=64)),
                ('usr_password', models.CharField(max_length=64)),
                ('usr_date', models.DateTimeField()),
                ('usr_email', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trans_buy_date', models.DateTimeField()),
                ('trans_sent_date', models.DateTimeField(null='True')),
                ('trans_recieved', models.BooleanField()),
                ('adrs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.addresses')),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_prod_amount', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('trans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('rev_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rev_score', models.IntegerField()),
                ('rev_text', models.CharField(max_length=15000, null='True')),
                ('rev_date', models.DateTimeField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('price_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_price', models.IntegerField()),
                ('price_date', models.DateTimeField()),
                ('prod_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
        migrations.AddField(
            model_name='addresses',
            name='usr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
    ]
