# Generated by Django 3.2.7 on 2023-12-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='usr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='prod_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
    ]
